// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuGTTWbyltOz2-FKiIs9UhKpib6GCS4TI',
    appId: '1:1008070353742:web:23a806c13d37f0c8af341f',
    messagingSenderId: '1008070353742',
    projectId: 'sanctuarai',
    authDomain: 'sanctuarai.firebaseapp.com',
    storageBucket: 'sanctuarai.firebasestorage.app',
    measurementId: 'G-TS087BH0P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC-PJY1FAPg0fIGSbsgViWQfO3NNf9UEs',
    appId: '1:1008070353742:android:facd06a33a168bfcaf341f',
    messagingSenderId: '1008070353742',
    projectId: 'sanctuarai',
    storageBucket: 'sanctuarai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVKue8iau0y_7JMLK0l0CSi-p6FhIXOGg',
    appId: '1:1008070353742:ios:20fa7c76329e92f8af341f',
    messagingSenderId: '1008070353742',
    projectId: 'sanctuarai',
    storageBucket: 'sanctuarai.firebasestorage.app',
    iosBundleId: 'com.example.sanctuarai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuGTTWbyltOz2-FKiIs9UhKpib6GCS4TI',
    appId: '1:1008070353742:web:d69ce74a961fa0ceaf341f',
    messagingSenderId: '1008070353742',
    projectId: 'sanctuarai',
    authDomain: 'sanctuarai.firebaseapp.com',
    storageBucket: 'sanctuarai.firebasestorage.app',
    measurementId: 'G-42ZXXPGH9E',
  );
}
